version: "3.5"
services:
  arbitrum-nitro.public.dappnode.eth:
    build:
      context: build
      args:
        UPSTREAM_VERSION: v2.1.0-beta.4
    volumes:
      - "data:/home/user/.arbitrum"
    environment:
      ETH_RPC_URL: "http://geth.dappnode:8545"
      EXTRA_OPTS: "--http.api=net,web3,eth,debug"
    image: "arbitrum-nitro.public.dappnode.eth:1.0.9"
    restart: unless-stopped
volumes:
  data: {}
