version: "3.5"
services:
  arbitrum-nitro.public.dappnode.eth:
    build:
      context: build
      args:
        UPSTREAM_VERSION: v2.0.10-73224e3
    volumes:
      - "data:/home/user/.arbitrum"
    environment:
      EXTRA_OPTS: "--http.api=net,web3,eth,debug"
    image: "arbitrum-nitro.public.dappnode.eth:1.0.7"
    restart: unless-stopped
volumes:
  data: {}
