version: "3.5"
services:
  arbitrum-nitro.public.dappnode.eth:
    build:
      context: build
      args:
        UPSTREAM_VERSION: v2.0.9-51f9452
    ports:
      - "8547"
      - "8548"
      - "9642"
    volumes:
      - "data:/home/user/.arbitrum"
    environment:
      EXTRA_OPTS: "--http.api=net,web3,eth,debug"
    image: "arbitrum-nitro.public.dappnode.eth:1.0.6"
    restart: unless-stopped
volumes:
  data: {}
