version: "3.5"
services:
  arbitrum-nitro.public.dappnode.eth:
    build:
      context: build
      args:
        UPSTREAM_VERSION: v3.0.0
    volumes:
      - data:/home/user/.arbitrum
    environment:
      ETH_EL_RPC_SOURCE: Global
      ETH_EL_CUSTOM: ""
      ETH_CL_RPC_SOURCE: Global
      ETH_CL_CUSTOM: ""
      INIT_SNAPSHOT_URL: https://snapshot.arbitrum.foundation/arb1/nitro-pruned.tar
      EXTRA_OPTS: "--http.api=net,web3,eth,arb,debug"
    image: arbitrum-nitro.public.dappnode.eth:1.0.12
    restart: unless-stopped
volumes:
  data: {}
